### ISSUE TITLE
Exception during pytest on the observer

### ISSUE THREAD

**Issue by typoman** [robotools/defcon#247]
I'm making a package that uses pytest and the module that the test is being performed on opens a UFO using `Font` from `defcon`. The module itself doesn't throw any errors, but in the tests that are being run by pytests it gives me this:

```
platform darwin -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: p/Tests, inifile: pytest.ini
collected 2 items                                                                                                                

this_test.py ..                                                                                                           [100%]

==================================================== 2 passed in 0.94 seconds ====================================================
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseObject.__del__ at 0x11012e950>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
```

The virtual environment is made of:
```
appdirs==1.4.3
booleanOperations==0.8.2
compreffor==0.4.6.post1
cu2qu==1.6.5
defcon==0.6.0
fontmake==1.10.1
fontMath==0.5.0
fontParts==0.8.7
fontPens==0.2.4
fonttools==3.43.2
fs==2.4.8
glyphsLib==4.0.0
lxml==4.3.4
MutatorMath==2.1.2
pyclipper==1.1.0.post1
pytz==2019.1
six==1.12.0
ufo2ft==2.9.1
unicodedata2==12.0.0
```
As you can the test pass because they assert to True. Inside the module, I just open ufo files, without performing any operations, just accessing data. The tests open multiple files and on every file that has opened, the above Traceback appears. I like to share the package but some parts of the package (e.g. ufo test files) I'm not allowed to share. I can make something smaller that narrows the problem so I can share it here if this information is not enough.

**Comment by benkiel** [comment]
Can you share a sample of the code you use to open a UFO and read data? That'd be enough to sort out the issue. To double check here: it's the pytest of your module, not defcon that is the issue, correct?

**Comment by typoman** [comment]
Yes, Traceback is from pytest running in my package, it's not from defcon test. I'm making a minimal test case for the issue.

**Comment by anthrotype** [comment]
I think it may have to do with the fact that defcon objects override `__del__` method but when the python interpreter exits it is not guaranteed to be called for objects that still exist, so any exceptions that occur during finalization are ignored and printed to stderr:
 
See https://docs.python.org/3/reference/datamodel.html#object.__del__

**Comment by typoman** [comment]
Could be, but I can't reproduce it in a small test case. Not sure what I did that caused it in my large package yet, still investigating.

**Comment by anthrotype** [comment]
the (ignored) exception message points to line 110 of defcon/tools/notifications.py:
https://github.com/robotools/defcon/blob/3e6f0071714c0ee0dfb69e4fe33c34c59e169b18/Lib/defcon/tools/notifications.py#L110

the exception complains that NoneType is not callable, and the only call is to `weakref.ref` function. It may be that when the interpreter is exiting, the `ref` function in `weakref` module is being cleaned up (i.e. set to `None`) so by the time the removeObserver method is called in one of the custom `__del__` methods it doesn't exist any more.

> __del__() can be executed during interpreter shutdown. As a consequence, the global variables it needs to access (including other modules) may already have been deleted or set to None.

Maybe try to hold a reference to that `weakref.ref` function as an attribute of NotificationCenter class, to prevent the garbage collector from deleting it beforehand.

Anyway I don't think this is a major issue.

**Comment by typoman** [comment]
Ok found it, I was loading the UFO files outside the test class with a global name like `UFO_FILES` which is an object that I made in my module. This object holds the defcon `Font` instances and I was using the `UFO_FILES` inside a test classe and methods. When I made the `UFO_FILES` property of the test class, Tracebacks went away.

You might ask why I loaded the files outside the test class. I was trying to cut the test time by loading the files only once. But now I have to load them inside every class. I'm going to stick to one test class for now.

**Comment by typoman** [comment]
For @benkiel, this is the data I was accessing:
```
font = Font(ufo_absolute_path)
family_name = font.info.familyName
style_name = font.info.styleName
```

**Comment by obi3wan** [comment]
What is this website?

**Comment by benkiel** [comment]
Reading this through, this was an issue with how the tests were constructed (loosing a reference to the UFO) than an issue in defcon. Closing.
