### ISSUE TITLE
FilesystemClosed error when loading glyph after font.save()

### ISSUE THREAD

**Issue by anthrotype** [robotools/defcon#311]
```python
>>> import defcon
>>> font = defcon.Font()
>>> font.newGlyph("a")
<defcon.objects.glyph.Glyph object at 0x111503fd0>
>>> path = "/tmp/ufo.ufo"
>>> font.save(path)
>>> print(font["a"])
<defcon.objects.glyph.Glyph object at 0x111503fd0>
>>> del font
>>> font = defcon.Font(path)
>>> font.save(path)
>>> print(font["a"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/clupo/Library/Python/3.7/lib/python/site-packages/defcon/objects/font.py", line 242, in _getitem_
    return self._glyphSet[name]
  File "/Users/clupo/Library/Python/3.7/lib/python/site-packages/defcon/objects/layer.py", line 247, in _getitem_
    self.loadGlyph(name)
  File "/Users/clupo/Library/Python/3.7/lib/python/site-packages/defcon/objects/layer.py", line 169, in loadGlyph
    self._stampGlyphDataState(glyph)
  File "/Users/clupo/Library/Python/3.7/lib/python/site-packages/defcon/objects/layer.py", line 579, in _stampGlyphDataState
    modTime = glyphSet.getGLIFModificationTime(glyphName)
  File "/Users/clupo/Library/Python/3.7/lib/python/site-packages/fontTools/ufoLib/glifLib.py", line 345, in getGLIFModificationTime
    return self.getFileModificationTime(fileName)
  File "/Users/clupo/Library/Python/3.7/lib/python/site-packages/fontTools/ufoLib/_init_.py", line 122, in getFileModificationTime
    dt = self.fs.getinfo(fsdecode(path), namespaces=["details"]).modified
  File "/Users/clupo/Library/Python/3.7/lib/python/site-packages/fs/wrapfs.py", line 138, in getinfo
    raw_info = _fs.getinfo(_path, namespaces=namespaces).raw
  File "/Users/clupo/Library/Python/3.7/lib/python/site-packages/fs/osfs.py", line 284, in getinfo
    self.check()
  File "/Users/clupo/Library/Python/3.7/lib/python/site-packages/fs/base.py", line 1553, in check
    raise errors.FilesystemClosed()
fs.errors.FilesystemClosed: attempt to use closed filesystem
>>> defcon.__version__
'0.7.2'
```

Also happens when installing from master.
Sorry I don't have time to investigate further.

**Comment by benkiel** [comment]
Just tested this with the latest Defcon, this is now fixed.

**Comment by benkiel** [comment]
Double checked, tested and works with latest version (`0.8.1`)
